name: Build
on:
  - push
  - pull_request
jobs:
  build_on_mac:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 19.3
      - name: create env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
      - name: install dependencies
        run: npm install
      - name: build
        run: npm run build:electron
